### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by chrisdone** [comment]
I think this should be an option passed to hindent in the config file or as a cmd arg, as it changes the AST itself (`parse . print . parse` /= id).

**Comment by cblp** [comment]
Why changing AST is bad?

But what is good:
1. It is idempotent.
2. It doesn't change semantics. Moreover, it unifies different codes with the same semantic.

Also
3. Tibbe's guide says imports must be sorted.

Config may be ok, too. Should it be on be default?

**Comment by cblp** [comment]
resolved conflicts

**Comment by chrisdone** [comment]
Being idempotent is good, being the identity morphism is good too. The problem for me with changing the code's AST is that it can influence editing, manual, structured or automatic editing. For example, with structured-haskell-mode, when I reformat, I can take the user back to the AST node they were at simply by coordinates. With this patch, the import I'm editing might jump elsewhere. Currently HIndent only (ostensibly) inserts or deletes whitespace characters (` `, `\n` and `{` and `}` in the case of `do`). It doesn't change ordering or the depth of the AST. If a refactoring tool HRefactor uses HIndent as its printer, it would need guarantee that only HRefactor made changes to the AST (even simple unit tests).

So I would suggest an option which is enabled by default, such as `allow-ast-changes` or something like that. Or perhaps: `allow-refactoring`. Or, more playfully, `NoEpimorphismRestriction`. Then users can benefit from refactoring types by default, but for other tooling or as a library, we can disable that.

**Comment by cblp** [comment]
The term "refactor" often mean more than just sorting imports. Like eta-reduction, or using class laws (fmap f . fmap g --> fmap (f . g)).

What about `allow-unify-ast`?

**Comment by chrisdone** [comment]
We might later support e.g. removing redundant parentheses or changing `X _ _` to `X{}`. Different syntactical terms which produce the same result.

I don't know what `allow-unify-ast` would mean. Perhaps we can just be more granular and think about this later. A simple `sort-imports` flag and be done with it.

**Comment by cblp** [comment]
> Currently HIndent only (ostensibly) inserts or deletes whitespace characters

Actually... no. Try

```haskell
data A
  deriving Show
```

or 

```haskell
module Foo (
  -- * Classes
  C(..),
  -- * Types
  -- ** A data type
  T,
  -- ** A record
  R,
  -- * Some functions
  f, g
  ) where
```

**Comment by wiz** [comment]
> A simple `sort-imports` flag and be done with it.

That's the flag I'll be expecting to toggle when concerned about something adjusting my imports.

**Comment by chrisdone** [comment]
@wiz Cool. In that case I'm 👍 on `sort-imports`.

**Comment by wiz** [comment]
After idling on it... Maybe this isn't a flag, but a setting instead? Like `imports: sort` or `imports: sort,align`. Or even a composite one:

```yaml
imports:
  collapse: false # clamp imports in one block
  sort: true # reorder
  vertical-align: true # stylish-haskell-like
```

**Comment by chrisdone** [comment]
`sort-imports`, `align-imports`, etc. also works. We're not going to be making so many options.

**Comment by cblp** [comment]
I prefer less options and less different styles. We must invent the one style that should be loved by everyone.

**Comment by chrisdone** [comment]
Nice addition to the test suite! Thanks!

**Pull request merged**
