### PR TITLE
Keep comments between case alternates; fixes #104

### LINKED ISSUE #104: Hindent removing comments in case statement
```haskell
-- |Main was getting a bit long, so I took the latter half of it and
-- put it into another function.
runTn :: IO ()
runTn = do
  -- First, initialize!
  initialize
  -- First, let's get the command line arguments
  args <- getArgs
  -- Then split'm up
  let fstarg = headMay args
      rstof = tailMay args
  -- Case statement them
  case fstarg of
    -- The default action is to edit today's entry
    Nothing -> editToday
    -- Otherwise...
    Just cmd ->
      case cmd of
        -- Edit a specific day
        "edit" ->
          case rstof of
            Just (s:_) ->
              case readMay s of
                Nothing -> help
                Just d  -> editEntry d
            _ -> help
        -- Otherwise just... well who cares at this point?
        _ -> help
```
Gets reformatted into

```haskell
-- |Main was getting a bit long, so I took the latter half of it and
-- put it into another function.
runTn :: IO ()
runTn = do
  -- First, initialize!
  initialize
  -- First, let's get the command line arguments
  args <- getArgs
  -- Then split'm up
  let fstarg = headMay args
      rstof = tailMay args
  -- Case statement them
  case fstarg of
    Nothing -> editToday
    Just cmd ->
      case cmd of
        "edit" ->
          case rstof of
            Just (s:_) ->
              case readMay s of
                Nothing -> help
                Just d  -> editEntry d
            _ -> help
        _ -> help
```

### PR DESCRIPTION
**Pull request by gibiansky**
Only affects `gibiansky` style. Will merge once Travis validates it.

### CODE REVIEW

**Comment by chrisdone** [comment]
You can push this directly.

**Comment by gibiansky** [comment]
If it's alright, I would prefer not to. I have learned from working with `ihaskell` recently that it's not a great idea to push directly to master if you're working with Travis -- while `hindent`'s test suite is fairly simple (for now) and only looks at one GHC version, in the long run, Travis will be testing things that I cannot test on my own computer (it's already testing dependency things that I'm not). So if I push directly to master, I can break the build unintentionally, and then have to scramble to fix this (or just let it stay broken for a while); on the other hand, if I make a PR and then merge it, i can wait until Travis verifies that the PR will merge without breaking anything.

It's a bit overkill for patches like this, but it seems like a good habit. Are there downsides to using PRs and waiting for travis to verify them? Alternatively, if you are worried about keeping a cleaner history, maybe the right answer is to make a PR, verify that it works, then rebase to update master from command-line (rather than pressing 'merge').

**Comment by chrisdone** [comment]
Okies I'll ignore these PRs in future unless explicitly asking for feedback.

**Comment by chrisdone** [comment]
I would prefer if you still just push the commit directly after verifying, yes.

**Comment by gibiansky** [comment]
Sounds good. In fact, I will try a slightly different approach -- develop on a branch *of `hindent`*, then wait for Travis, then rebase. This avoids the noiseness of a PR, while also gets verified by travis before being in master.

**Comment by chrisdone** [comment]
Right, I was thinking; doesn't travis still build other branches anyway?

**Comment by gibiansky** [comment]
Yes, it does.

**Pull request merged**
