### PR TITLE
implementation for `ParComp` -- parallel list comprehension

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by chrisdone** [comment]
Can you make the commas and bars line up?

**Comment by cblp** [comment]
Of course, but it would be less readable (as for me). My intention was to show clearly "parallel" groups of "sequential" statements.

**Comment by cblp** [comment]
```haskell
fun xs ys =
  [ (alphaBetaGamma, deltaEpsilonZeta)
  | x <- xs
  , z <- zs
  | y <- ys
  , cond
  , let t = t
  ]
```

Do you find it readable perfectly?

**Comment by chrisdone** [comment]
Yep, like that.

The additional indentation looks a bit odd to me. _(subjective opinion)_

Otherwise adding a parallel comprehension would suddenly indent unrelated ones which is unnecessary and increases the size of diffs. _(objective problem)_

**Comment by cblp** [comment]
Lined commas and bars.

**Comment by chrisdone** [comment]
Great!

**Pull request merged**
