### PR TITLE
Performance Improvements

### PR DESCRIPTION
**Pull request by ennocramer**
In my benchmarks, these changes improve pretty printing performance and memory allocation by an order of magnitude.  Please review.

### CODE REVIEW

**Comment by gibiansky** [comment]
This is great! Does the test suite still pass locally for you? (Travis config seems to be outdated)

**Comment by chrisdone** [comment]
Oooo! Sounds lovely. All the tests pass for me.

**Comment by chrisdone** [comment]
I have to go AFK for the weekend but I'll merge now and on Monday do some sanity tests, and if all looks well, do a release to Hackage.

**Comment by gibiansky** [comment]
@ennocramer By the way, how did you benchmark `hindent`?

**Comment by ennocramer** [comment]
I did verify the test suite and performed some sanity checks against some of my own code. 

My understanding of the semantics of `depend` are that checking line and column numbers are sufficient, but I might be wrong here.

I believe the new comment annotation code will find the same AST node as before, but I did not specifically test for it beyond 'unit test still work' and 'my code still formats the same'.

**Comment by gibiansky** [comment]
What I meant was how did you get performance numbers -- I'd like to do some benchmarking on my own to see if my own style can be improved, or if there are still big gains lurking somewhere :) If you have any code or helpers to benchmark it I could re-use them.

**Comment by ennocramer** [comment]
@gibiansky I just repeatedly compiled hindent with `stack build --profile`, and ran `hindent +RTS -p`.

The first change came about when I saw that `==` was a significant cost center and I did not feel that was justified. I did not expect that change to have such an impact though.

After that change the profile showed the `processComment` function as the single most important factor, so I read that function, saw that it did a lot of linear searches and just went about rewriting it.

**Comment by chrisdone** [comment]
@ennocramer @gibiansky I added a trivial benchmark suite. This more than doubled the speed of every style! Nice job!

```
benchmarking Main/BigDeclarations/HIndent.reformat: "fundamental"
time                 3.869 ms   (3.833 ms .. 3.902 ms)
                     0.999 R²   (0.998 R² .. 0.999 R²)
mean                 3.966 ms   (3.929 ms .. 4.013 ms)
std dev              139.9 μs   (106.4 μs .. 183.8 μs)
variance introduced by outliers: 17% (moderately inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "chris-done"
time                 559.1 ms   (NaN s .. 566.4 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 564.7 ms   (562.0 ms .. 566.9 ms)
std dev              3.637 ms   (0.0 s .. 3.913 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "johan-tibell"
time                 2.032 s    (2.003 s .. 2.048 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.027 s    (2.019 s .. 2.031 s)
std dev              6.543 ms   (0.0 s .. 7.178 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "gibiansky"
time                 28.15 ms   (27.88 ms .. 28.37 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 28.02 ms   (27.90 ms .. 28.15 ms)
std dev              267.0 μs   (225.9 μs .. 327.4 μs)

benchmarking Main/BigDeclarations/HIndent.reformat: "cramer"
time                 19.02 ms   (18.80 ms .. 19.20 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 18.90 ms   (18.83 ms .. 18.98 ms)
std dev              199.1 μs   (157.7 μs .. 267.2 μs)
```

->

```
benchmarking Main/BigDeclarations/HIndent.reformat: "fundamental"
time                 2.443 ms   (2.371 ms .. 2.550 ms)
                     0.987 R²   (0.980 R² .. 0.993 R²)
mean                 2.560 ms   (2.501 ms .. 2.624 ms)
std dev              205.8 μs   (178.1 μs .. 252.1 μs)
variance introduced by outliers: 57% (severely inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "chris-done"
time                 122.4 ms   (117.3 ms .. 127.7 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 116.0 ms   (113.8 ms .. 118.5 ms)
std dev              3.533 ms   (2.740 ms .. 4.453 ms)
variance introduced by outliers: 11% (moderately inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "johan-tibell"
time                 342.9 ms   (332.3 ms .. 354.5 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 345.2 ms   (343.2 ms .. 347.1 ms)
std dev              2.986 ms   (67.99 as .. 3.142 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking Main/BigDeclarations/HIndent.reformat: "gibiansky"
time                 7.844 ms   (7.715 ms .. 7.964 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 7.790 ms   (7.727 ms .. 7.863 ms)
std dev              191.2 μs   (153.9 μs .. 258.4 μs)

benchmarking Main/BigDeclarations/HIndent.reformat: "cramer"
time                 6.014 ms   (5.945 ms .. 6.091 ms)
                     0.999 R²   (0.997 R² .. 0.999 R²)
mean                 6.002 ms   (5.955 ms .. 6.077 ms)
std dev              175.1 μs   (127.9 μs .. 271.8 μs)
variance introduced by outliers: 12% (moderately inflated)
```

**Pull request merged**
