### PR TITLE
align qualified imports with unqualified ones

### PR DESCRIPTION
**Pull request by cblp**
This change is [Reviewable](https://reviewable.io/reviews/chrisdone/hindent/332)

### CODE REVIEW

**Comment by cblp** [comment]
Sorry, I've found an error. Fixing.

**Comment by cblp** [comment]
Fixed.

**Comment by tfausak** [comment]
I'm not a fan of this style. It adds a bunch of extra space for basically no reason.

**Comment by cblp** [comment]
@tfausak Readability is the reason. It is much more simpler to read imports and find the interesting ones if they are aligned and sorted, as in dictionaries.

Unfortunately, Haskell syntax forces us to add extra space. Maybe it needs to be revised.

**Comment by cblp** [comment]
@tfausak do you know how to achieve readability without extra space?

**Comment by tfausak** [comment]
I think it's readable as is. 

I do see the appeal of having every module name start on the same column. Package imports mess that up a little, as do long lists of identifiers to import. But it isn't any more readable to me. And I hate how it looks when you don't have any qualified imports; there's a big space for no reason.

**Comment by cblp** [comment]
Where no qualified import are, they may appear tomorrow.

Aligned imports are much more readable for me.

I started a twitter poll to find what other people think. https://twitter.com/cblp_su/status/785855971960713216 Maybe I am wrong.

**Comment by tfausak** [comment]
Sure, if there are no qualified imports you could remove the extra space. But then when you add a qualified import you have to change all the other lines.

``` hs
import Data.Function
```

``` diff
1c1,2
< import Data.Function
---
> import           Data.Function
> import qualified Data.Map as Map
```

**Comment by cblp** [comment]
@tfausak indeed. That's why there always should be extra space.

**Comment by gibiansky** [comment]
For better or worse I think the spaces before qualified imports are pretty common (dare I say "standard") already... so might as well make them automated rather than have people do this by hand

**Comment by cblp** [comment]
See also https://github.com/ghc-proposals/ghc-proposals/pull/21

**Comment by s9gf4ult** [comment]
Diffs blow, as mentioned above is the main malfunction of such code style.

**Comment by cblp** [comment]
@s9gf4ult in which case do diffs blow?

**Comment by s9gf4ult** [comment]
@cblp in case when you firstly have imports like

```haskell
import Data.Blah
import Control.Foo
```

and then you have

```haskell
import           Data.Blah
import           Control.Foo
import qualified Data.Map as M
```

because imports must be segmented like this 

```haskell 
import Data.Blah
import Control.Foo
                 
import qualified Data.Map as M
```
, xor we must implement https://github.com/cblp/ghc-proposals/blob/patch-2/proposals/0000-relax-qualified-import-syntax.rst so alignment and segmentation becomes useless.

**Comment by cblp** [comment]
@s9gf4ult oh, blowing diffs have been discussed earlier:
- https://github.com/chrisdone/hindent/pull/332#issuecomment-252947598
- https://github.com/chrisdone/hindent/pull/332#issuecomment-252953670

I'm afraid, that proposal is distant future.

**Comment by chrisdone** [comment]
I think this is just a trade-off. 

* Do you want visually aligned module names?
* Do you want clean diffs?

If you answered yes to both of these, then the cost is that you have
always-indented imports. Including the silly ones that look like this:

``` haskell
import           GHC.Generics
```

It's silly but it's not our fault Haskell designers made a syntax that
changes the column number of the module name.

I'm leaving this for a bit more community feedback but personally I
lean towards merging.

**Comment by chrisdone** [comment]
Maybe with such community division we can make this a flag. Turned on by default and then an option to disable it for those who don't like it.

**Comment by chrisdone** [comment]
(I think that's generally a pretty good way forward. We go with a decision that seems standard, and if it's a bit contentious then we add a config option to turn it off.)

**Comment by cblp** [comment]
I quit using hindent in everyday coding. Anybody may pick up this branch.

**Pull request closed without merging**
