### PR TITLE
gibiansky style: fix forgotten comments after let, add test

### PR DESCRIPTION
**Pull request by gittywithexcitement**

### CODE REVIEW

**Comment by gittywithexcitement** [comment]
I also noticed that `printComments After` was not paired with `printComments Before` in two other places: 
```
rhss (GuardedRhss _ rs) =
decls (FunBind _ matches) =
```

Are these bugs as well?

**Comment by gittywithexcitement** [comment]
Hi @gibiansky, any response to my question in previous comment? Are those bugs?

**Comment by gibiansky** [comment]
@gittywithexcitement Apologies, missed the comment. 

I am not sure whether those are bugs – it's quite possible that they are. If you can use the knowledge that there's a missing `printComments After` to find code that gets its comment dropped, it's a bug. I'm not 100% sure that it can happen, though.

**Comment by gittywithexcitement** [comment]
Yes, those other two missing locations were errors. See https://github.com/chrisdone/hindent/pull/135

**Pull request merged**
