### PR TITLE
sort imports by package and qualification, sort import specs and their components

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by cdepillabout** [comment]
This seems to ignore the recommendation for "grouping imports" from the style guide:

https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#imports

What do people think about this?  Should all imports just be sorted in one alphabetical list (as opposed to grouping them by where they came from)?

**Comment by cblp** [comment]
@cdepillabout, no, this sorts each group separately.

**Comment by cdepillabout** [comment]
@cblp So if you had something like this:

```haskell
module MyLib.Foo where

import Data.Maybe
import Control.Monad

import Data.Text
import Data.Text.Lazy

import MyLib.Zap
import MyLib.Bar
```

I had assumed it would be formatted like this:

```haskell
module MyLib.Foo where

import Control.Monad
import Data.Maybe
import Data.Text
import Data.Text.Lazy
import MyLib.Bar
import MyLib.Zap
```

But you're saying it would actually be formatted like this?

```haskell
module MyLib.Foo where

import Control.Monad
import Data.Maybe

import Data.Text
import Data.Text.Lazy

import MyLib.Bar
import MyLib.Zap
```

**Comment by cblp** [comment]
@cdepillabout, yes. I've tried right now.

**Comment by cdepillabout** [comment]
Okay, great.  Thanks for clearing that up! :+1:

It might be nice to have an example/test showing this.

**Comment by cblp** [comment]
@cdepillabout sure! Added.

**Pull request closed without merging**
